parsing:
  regex_patterns:
    barcode: 
      - "(\\(01\\)[0-9]+\\(17\\)[0-9]+\\(10\\)[0-9]+)"
    expiry_date: 
      - "(..?/..?/..)"
    gtin-14: 
      - "\\(01\\)([0-9]+)"
      - ""
    label_number: 
      - "([0-9]+) A conserver"
      - "([0-9]+) .+ X[0-9]"
    lot_number: 
      - "\\(10\\)([0-9]+)"
    product_name: 
      - "([A-Z ]{5,})"
    quantity: 
      - "x|X([0-9])"
supplier:
  logo_path: logo/logo-relay.png
  name: relay
